### PR TITLE
force encoding to utf-8 on file operation

### PR DESCRIPTION
**Pull request by xajkep**

### CODE REVIEW

**Comment by vsoch** [comment]
Thanks for the PR @xajkep ! Could you please give a little more context about this change?
 - what issues you encountered to warrant it
 - what it means for support of older versions of Python

And if we decide to integrate, could you please update the CHANGELOG and bump the version in version.py?

**Comment by matej2** [comment]
This might be a better fix than #38. Different environments can cause encoding issues.

**Comment by vsoch** [comment]
Indeed I was just reviewing the other - and I like this one much better! Can you confirm it fixes the issue for you? If yes, could you please bump the version in schemaorg/version.py to 0.1.1 and add a note to the CHANGELOG for this update?

**Comment by matej2** [comment]
I just confirmed it fixes the issue. I ran this code example: https://github.com/openschemas/schemaorg/tree/master/examples/require-all#3-get-nested-types-and-properties

It seems I cannot fork a fork (it would fork your repo, not @xajkep).  You can try merging this, meanwhile I can create separate PR with changes

**Comment by vsoch** [comment]
Awesome! Yeah if you want to pull in the commits here if I merge in another PR they will be included. but also I'm good to wait for the author here to update the PR.

**Review by vsoch — APPROVED** [review]

**Pull request merged**
